### ISSUE TITLE
create extended cleanReports

### ISSUE THREAD

**Issue by sumangongali** [jmeter-gradle-plugin/jmeter-gradle-plugin#62] opened 2016-04-25 14:02 UTC
createExtended reports must clean every log and results literally there must not be any log including jmeter.log

**Comment by foragerr** [comment] 2016-04-25 16:42
do you mean `jmclean`?

**Comment by sumangongali** [comment] 2016-04-25 17:39
Yes jmClean only clears the current run reports ,but a clear clean is required as well.

**Comment by foragerr** [comment] 2016-04-25 17:46
Agreed

**Comment by foragerr** [comment] 2016-04-27 00:45
Unable to reproduce:

so the task `jmClean` currently deletes the entire jmeter-report directory and recreates it - this deletes everything including jmeter log. Added an additional line to delete jmeter log even if it's location is customized.

**Comment by foragerr** [comment] 2016-04-27 00:51
Closing this for now, please feel free to reopen if I misunderstood the issue report.

**Closed as completed** 2016-04-27 00:50 UTC
Labels: enhancement
