### ISSUE TITLE
new to gradle questions

### ISSUE THREAD

**Issue by kmacpher67** [jmeter-gradle-plugin/jmeter-gradle-plugin#51] opened 2016-04-08 13:16 UTC
Very well done! 
Simple clean, install, just works with IntellJ, IDEA 15 gradle plugin, Spring Boot, Gradle mix. 
- spring-boot-gradle-plugin:1.3.2,
  -  using  gradle-2.6 wrapper. 

I'm new to gradle, otherwise I'd go dig into a file somewhere and figure out what it's doing. 

How do I get jmRun to run as part of build process or test task? 
Does jmReport Automatically run as rmRun sub-task, does this need to be specified separately? 
In terms of jmClean, does this automatically run, is there a problem with left over report artifacts? 
    - Experience suggestions on when to run jmClean task?  

If I want to specify a specific .jmx file for an environment or reason like that, how can do pseudo-code like this: 

```
if (env==X)
      jmRun( jmTestFiles["DemoX.jmx"] )
else
      rmRun( jmTestFiles["Demo.jmx"])  
```

I'm sorry if this is more gradle ("ish") questions, but that's the kewlest part of this, this is so sick easy it's on deck to be check into our teams standard build and candidate for entire project!

I was thinking of having the devs localhost system (which is configured differently than test-dev, integration1, and qa, etc) have this environments be tested incrementally as the build moves through the process. As data, urls, hosts, protocol, passwords, usernames, change, the test code could be loaded dynamically and automatically, thus providing us a valid smoke test all the way through the pipeline until it gets out of our realm.

**Comment by foragerr** [comment] 2016-04-08 19:21
Thank you! It is always nice to hear good stuff from end users :)

I have kept the jm tasks modular and separate from each other and from regular gradle java tasks, by design. The intent was to keep each task as stateless as possible. This way each task is always optional and never forced upon any other task groups including build or test - jmRun can take a while to run sometimes and you may not want to run it every time you run `gradle check`. If you're doing your own reporting - using jenkins performance plugin for instance, it should be easy to decouple this plugin's reporting - which means `jmReport` is not automatically run after `jmRun`

I would say Gradle encourages this design because it is then very easy to attach tasks to other tasks and chain them up in any combination you want. Two useful gradle mechanisms are dependsOn and finalizedBy.

```
TaskX.finalizedBy(TaskY)
```

will ensure that TaskY is always executed when your call `gradle TaskX` and it is successful.

```
TaskX.dependsOn(TaskY)
```

will ensure TaskY is executed _before_ TaskX when you call `gradle TaskX`. There are also mustRunAfter and shouldRunAfter that you can use to control the order in which gradle tasks are run.

In a continuous integration setup, if you always start with a clean workspace, there is no need to run `jmClean` ever. If you retain workspace, it makes sense to run it in every build, just before `jmRun`

**Comment by foragerr** [comment] 2016-04-08 19:41
Gradle lets you write any arbitrary groovy code in the build script, which means you can do stuff like:

```
jmeter{ 
    if (env=='X') jmTestFiles = ["DemoX.jmx"]
    else jmTestFiles = ["Demo.jmx"]
}
```

However, If your jmx files are pretty much the same except for some environment config params like hostnames or urls etc, I would recommend you _not_ have two jmx files just from the DRY point of view. Two places to maintain the same test steps isn't ideal. You should instead parametrize the environment variables and then pass actual values either using `jmUserProperties` in build.gradle or [from the command line](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/44) at execution time.

**Comment by foragerr** [comment] 2016-04-13 01:03
@kmacpher67 Does this answer your questions? Can I close this issue?

**Comment by foragerr** [comment] 2016-04-14 12:50
@kmacpher67 I'm closing this issue, feel free to reopen if you have further questions.

**Closed as completed by foragerr** 2016-04-14 12:50 UTC
